package Client;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.awt.*;
import java.util.Iterator;
import java.util.Vector;
import static sun.org.mozilla.javascript.internal.Context.exit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PK
 */
public class ClientForm extends javax.swing.JFrame {

    /**
     * Creates new form ClientForm
     */
    
    Socket server = null;
    DataInputStream in = null;
    DataOutputStream out = null;
    Vector<String> q = null;
    Vector<String> groups = null;
    String username = "anonymous";
    String groupname = "public";
    boolean online = false;
    
    public ClientForm() {
        initComponents();
        //this.txt_in.setEnabled(false);
        this.setLocationByPlatform(true);
        this.setTitle("Terminal Chat Lite 0.4b");
        groups = new Vector<String>();
        q = new Vector<String>();
        try {
            // TODO add your handling code here:
            server = new Socket("127.0.0.1",2122);
            in = new DataInputStream(server.getInputStream());
            out = new DataOutputStream(server.getOutputStream());
            JOptionPane.showMessageDialog(null, "Connected to server.");
            online = true;
            ReceiveMessage clientThread = new ReceiveMessage(in,txt_msg,this);
            clientThread.setDaemon(true);
            clientThread.start();
        } catch (UnknownHostException ex) {
            JOptionPane.showMessageDialog(null, "Connected failed!");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Fail");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_msg = new javax.swing.JTextArea();
        txt_in = new javax.swing.JTextField();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_msg.setEditable(false);
        txt_msg.setColumns(20);
        txt_msg.setRows(5);
        txt_msg.setText("Terminal Chat Version 0.4 Beta");
        jScrollPane1.setViewportView(txt_msg);

        txt_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_inActionPerformed(evt);
            }
        });
        txt_in.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_inKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addComponent(txt_in))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_inActionPerformed

    private void txt_inKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_inKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            send();
        }
    }//GEN-LAST:event_txt_inKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new ClientForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField txt_in;
    private javax.swing.JTextArea txt_msg;
    // End of variables declaration//GEN-END:variables

    private void send() {
        try {
            // TODO add your handling code here:
            String msg = txt_in.getText();
            if(msg.startsWith("#")){
                //Command string do not encapsulate msg
                try{
                    String localCommand = msg.substring(1,msg.indexOf(" "));
                    String param = msg.substring(msg.indexOf(" ")).trim();
                    System.out.println("'" + localCommand + "' '" + param + "'");
                    //end get input
                    if(localCommand.equalsIgnoreCase("create")){
                        this.groups.add(param);
                    }
                    else if(localCommand.equalsIgnoreCase("join")){
                        this.groups.add(param);
                        this.groupname = param;
                    }
                    else if(localCommand.equalsIgnoreCase("leave")){
                        this.groups.remove(groupname);
                        this.groupname = "public";
                    }
                    else if(localCommand.equalsIgnoreCase("hostname")){
                        this.username = param;
                    }
                    else if(localCommand.equalsIgnoreCase("enter")){
                        if(this.groups.contains(param));
                        this.groupname = param;
                    }
                    else if(localCommand.equalsIgnoreCase("mute")){
                        this.online = false;
                    }
                    else if(localCommand.equalsIgnoreCase("unmute")){
                        this.online = true;
                        for (Iterator<String> it = q.iterator(); it.hasNext();) {
                            String unread = it.next();
                            unread.substring(0, unread.indexOf(" ")).equalsIgnoreCase(groupname);
                            String groupname = msg.substring(0,msg.indexOf(" "));
                            String tmp = msg.substring(msg.indexOf(" ") + 1);
                            String username = tmp.substring(0,tmp.indexOf(" "));
                            String txt = tmp.substring(tmp.indexOf(" ") + 1);
                            msg = username + ": " + txt;
                            txt_msg.append("\n" + msg);
                            System.out.println(msg);
                        }
                    }
                    else if(localCommand.equalsIgnoreCase("exit")){
                        exit();
                    }
                    else if(localCommand.equalsIgnoreCase("list")){
                        txt_in.setText("-list");
                        this.send();
                    }
                }
                catch(Exception ex){
                    System.out.println("Error wrong input");
                    this.txt_msg.append("\n'" + msg + "' is not recognized as an internal or external command.");
                }
            }
            else{
                if(!msg.equalsIgnoreCase("-list")){
                    msg = groupname + " " + username + " " + msg;
                }
                out.writeUTF(msg);
            }
        } catch (IOException ex) {
            Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
        } finally{
            txt_in.setText("");
        }
    }
}
